// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"database/sql"
)

type Account struct {
	ID                     string
	Email                  string
	EmailVerified          bool
	EmailVerificationToken sql.NullString
	TimeEmailVerified      sql.NullTime
	Phone                  sql.NullString
	PhoneVerified          bool
	PhoneVerificationCode  sql.NullString
	TimePhoneVerified      sql.NullTime
	Password               string
	Flags                  int64
	TimeCreated            sql.NullTime
}

type Organization struct {
	ID          string
	Owner       string
	TimeCreated sql.NullTime
}
