// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: query.sql

package db

import (
	"context"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts(id, email, password) VALUES($1,$2,$3) RETURNING id
`

type CreateAccountParams struct {
	ID       string
	Email    string
	Password string
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (string, error) {
	row := q.db.QueryRow(ctx, createAccount, arg.ID, arg.Email, arg.Password)
	var id string
	err := row.Scan(&id)
	return id, err
}
